apiVersion: v1
kind: ReplicationController
metadata:
  name: hello
  labels:
    run: hello
spec:
  replicas: 2
  selector:
    run: hello
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - name: hello
        image: hello
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /hello/v1/hello
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 1
